name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Run Unit Tests (Jest)
      run: npm test

    - name: Setup Clasp
      run: npm install -g @google/clasp

    - name: Create Clasp Credentials
      env:
        CLASP_SECRET: ${{ secrets.CLASP_SECRET }}
      run: |
        echo "$CLASP_SECRET" > ~/.clasprc.json

    - name: Validate Clasp Credentials
      run: |
        if ! jq -e .token ~/.clasprc.json > /dev/null; then
          echo "::error::Invalid Clasp Secret! The ~/.clasprc.json file is missing the 'token' property."
          echo "Check that you copied the ENTIRE content of the file, starting with '{' and containing 'token': {...}'"
          exit 1
        fi


    
    - name: Configure Test Environment
      run: echo '{"scriptId":"1zbeOxqz_idbx9ngWy9wowUigNW94-G0o5FNWXRi-IJ3L35h7dCQpUicO","rootDir":""}' > .clasp.json

    - name: Deploy to Test Script
      run: clasp push --force

    - name: Run Integration Test (Bess Sheet)
      run: clasp run TestBessTAndASheet
